### ISSUE TITLE
Catch Ctrl+C

### ISSUE THREAD

**Issue by LordOfTheRats** [WinTeach/pykib#1]
PyKib does not react to Ctrl+C on its parent console. That's a known Python thing and quite easy to fix. See https://gist.github.com/rtfpessoa/e3b1fe0bbfcd8ac853bf

Would be nice to have for developing and debugging :)

**Comment by WinTeach** [comment]
I've included a sigterm handler in the latest devel build.
It wasn't as easy like described in the linked git file. 
The python interpreter which takes care about the signals will not react as long the QT event loop is running and no python function is called.
To force the interpreter to run from time to time i've included a timer which executes each second.

Source: https://stackoverflow.com/questions/4938723/what-is-the-correct-way-to-make-my-pyqt-application-quit-when-killed-from-the-co
