### ISSUE TITLE
Windows Builds

### ISSUE THREAD

**Issue by LordOfTheRats** [WinTeach/pykib#2]
Are Windows builds possible? I have a potential usecase for that.

**Comment by WinTeach** [comment]
First Windows build for 64bit system is available for download in the release section. I will try to build a 32bit Version later this week.

**Comment by WinTeach** [comment]
There wan't be a windows 32bit version available in the next time. For this i would have to compile the whole qt enviremont by myself because no suitable QTWebenginge moduls is available out there
