### ISSUE TITLE
Auto Login Option

### ISSUE THREAD

**Issue by eXplOiD1** [WinTeach/pykib#5]
Hello is there an Option to Autologin into an Https:// page ?

**Comment by WinTeach** [comment]
Hi  eXplOiD1,
sorry for the late response, i didn't see your request. I've to check the notification settings.

If you mean with Autologin an HTTP-Basic Authentification, then it is possible in the same way like with Chrome and Firefox. You can pass your login data for the site within the url like this:
https://%username%:%password%@yourdomain.com

There are no other Autologin features included.

Best Regards,
Tobias

**Comment by WinTeach** [comment]
Since devel build c5293fe there is another kind of autologin mechanism included. You're now be able to set login credentials for any kind of website on the command line. The browser is autologin feture is preconfigured for the usage with Citrix Storefront an RDWeb sites, but it is also possible to configure own field ids where the userdata has to be pushed in.

**Comment by eXplOiD1** [comment]
Thank you very much,
i will Test it and respond to you

________________________________
Von: tobias@winteach.de <notifications@github.com>
Gesendet: Friday, August 9, 2019 1:56:52 PM
An: WinTeach/pykib <pykib@noreply.github.com>
Cc: eXplOiD <exploid@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [WinTeach/pykib] Auto Login Option (#5)


Since devel build c5293fe<https://github.com/WinTeach/pykib/commit/c5293fe50017e37f3c1e53d0c7848da117e92b55> there is another kind of autologin mechanism included. You're now be able to set login credentials for any kind of website on the command line. The browser is autologin feture is preconfigured for the usage with Citrix Storefront an RDWeb sites, but it is also possible to configure own field ids where the userdata has to be pushed in.

**Comment by eXplOiD1** [comment]
Traceback (most recent call last):
  File "pykib.py", line 24, in <module>
    import pykib_base.ui
  File "C:\Users\eXplOiD\Desktop\pykib-devel\pykib_base\ui.py", line 20, in <module>
    from PyQt5 import QtCore, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

After Trying to start with Console.
